name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 20
      uses: actions/setup-java@main
      with:
        java-version: '20'
        distribution: 'temurin'
        cache: gradle
    - name: Setup Node.js environment
      uses: actions/setup-node@main
      with:
        node-version: latest
    - name: Build with Gradle
      run: rm -rf .git/hooks;rm -rf android;mkdir dist;npm install;npx vite build;npx cap add android;npx cap sync;cd android;ls -lah;chmod +x gradlew;./gradlew build --warning-mode all
